apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-datadir-pvc-1
  namespace: default
spec:
   volumeName: redis-datadir-pv-1
   accessModes:
      - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
